//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 病害
    /// </summary>
    public partial class FM_Disease
    {
        /// <summary>
    	/// 病害类型
    	/// </summary>
        public string Disease_Type { get; set; }
        /// <summary>
    	/// 管片名称
    	/// </summary>
        public string GP_Name { get; set; }
        /// <summary>
    	/// 主键
    	/// </summary>
        public string Id { get; set; }
    }
}
